<?php

/**
 * BaseRandomAutoComplete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRandomAutoComplete extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('random_auto_complete');
    }

    public function setUp()
    {
        parent::setUp();
        $mus_autocompletable0 = new Mus_AutoCompletable(array(
             ));
        $this->actAs($mus_autocompletable0);
    }
}