<?php

/**
 * BasePostAutoComplete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property Post $Post
 * 
 * @method integer          getPostId()  Returns the current record's "post_id" value
 * @method Post             getPost()    Returns the current record's "Post" value
 * @method PostAutoComplete setPostId()  Sets the current record's "post_id" value
 * @method PostAutoComplete setPost()    Sets the current record's "Post" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostAutoComplete extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_auto_complete');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $mus_autocompletable0 = new Mus_AutoCompletable(array(
             'relation' => 
             array(
              'Post' => 
              array(
              'defaultScore' => 50,
              ),
             ),
             ));
        $this->actAs($mus_autocompletable0);
    }
}