<?php

/**
 * BaseThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property array $posts_status_number
 * @property Doctrine_Collection $Posts
 * 
 * @method string              getTitle()               Returns the current record's "title" value
 * @method array               getPostsStatusNumber()   Returns the current record's "posts_status_number" value
 * @method Doctrine_Collection getPosts()               Returns the current record's "Posts" collection
 * @method Thread              setTitle()               Sets the current record's "title" value
 * @method Thread              setPostsStatusNumber()   Sets the current record's "posts_status_number" value
 * @method Thread              setPosts()               Sets the current record's "Posts" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseThread extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('thread');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('posts_status_number', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'thread_id'));
    }
}