<?php

/**
 * BasePostAutoComplete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property integer $post_id
 * @property integer $score
 * @property Post $Post
 * 
 * @method string           getTitle()   Returns the current record's "title" value
 * @method integer          getPostId()  Returns the current record's "post_id" value
 * @method integer          getScore()   Returns the current record's "score" value
 * @method Post             getPost()    Returns the current record's "Post" value
 * @method PostAutoComplete setTitle()   Sets the current record's "title" value
 * @method PostAutoComplete setPostId()  Sets the current record's "post_id" value
 * @method PostAutoComplete setScore()   Sets the current record's "score" value
 * @method PostAutoComplete setPost()    Sets the current record's "Post" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostAutoComplete extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post_auto_complete');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $autocompletable0 = new AutoCompletable(array(
             'relations' => 
             array(
              'Post' => 
              array(
              'defaultScore' => 50,
              'defaultNullScore' => 1,
              'foreignAlias' => 'AutoCompleteRecord',
              'className' => 'Post',
              'scoreColumn' => 'score',
              'stringColumn' => 'name',
              ),
             ),
             ));
        $this->actAs($autocompletable0);
    }
}