<?php

/**
 * BaseAnotherThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $status
 * @property integer $referenceId
 * @property string $referenceType
 * 
 * @method string        getTitle()         Returns the current record's "title" value
 * @method string        getStatus()        Returns the current record's "status" value
 * @method integer       getReferenceId()   Returns the current record's "referenceId" value
 * @method string        getReferenceType() Returns the current record's "referenceType" value
 * @method AnotherThread setTitle()         Sets the current record's "title" value
 * @method AnotherThread setStatus()        Sets the current record's "status" value
 * @method AnotherThread setReferenceId()   Sets the current record's "referenceId" value
 * @method AnotherThread setReferenceType() Sets the current record's "referenceType" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnotherThread extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('another_thread');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('referenceId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('referenceType', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}