<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/21 19:22:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'predator',
  'name' => 'doctrine',
)),);
