<?php

/**
 * AnotherThread1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnotherThread1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnotherThread1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnotherThread1');
    }
}