<?php

/**
 * AnotherThreadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnotherThreadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnotherThreadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnotherThread');
    }
}