<?php

/**
 * PostCloneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostCloneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostCloneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostClone');
    }
}