<?php

/**
 * PostAutoCompleteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostAutoCompleteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostAutoCompleteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostAutoComplete');
    }
}