<?php

/**
 * RandomAutoCompleteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RandomAutoCompleteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RandomAutoCompleteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RandomAutoComplete');
    }
}