<?php

/**
 * PluginPostCloneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPostCloneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPostCloneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPostClone');
    }
}