<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/22 15:18:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 123123,
  'name' => 'doctrine',
)),);
