<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/06 10:50:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'predator',
  'name' => 'doctrine',
)),);
