<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2013/02/24 15:29:37
=======
// date: 2013/02/22 15:57:11
>>>>>>> 5e17578e167afd95d1e3ec2dd81dd77131f1b921
sfConfig::add(array(
  'mod_job_enabled' => true,
  'mod_job_view_class' => 'sfPHP',
));
