<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2013/02/24 15:29:37
=======
// date: 2013/02/22 15:57:11
>>>>>>> 5e17578e167afd95d1e3ec2dd81dd77131f1b921
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
);
